"""
Configuration package for the chat_to application.

This package contains all configuration modules for the application.
"""

from .ollama_models import (
    CHAT_MODEL,
    EMBEDDINGS_INDEXER_MODEL,
    EMBEDDINGS_KB_MODEL,
)
from .server_config import (
    HOST,
    PORT,
    OLLAMA_URL,
    MAX_UPLOAD_SIZE,
    ALLOWED_BOOK_EXTENSIONS,
    ALLOWED_AVATAR_EXTENSIONS,
    DATA_DIR,
    CHARACTERS_DIR,
    BOOKS_DIR,
    AVATARS_DIR,
    GROUPS_DIR,
    CHROMA_DIR,
)
from .chunking_config import (
    CHUNK_SIZE,
    OVERLAP_PERCENTAGE,
    OVERLAP_SIZE,
)
from .tts_config import (
    TTS_SERVICE_URL,
    TTS_TIMEOUT,
    TTS_OUTPUT_DIR,
    TTS_MAX_TEXT_LENGTH,
)
from .stt_config import (
    STT_SERVICE_URL,
    STT_TIMEOUT,
    STT_MAX_FILE_SIZE,
    STT_ALLOWED_FORMATS,
)
from .group_chat_config import (
    MAX_CHARACTERS_PER_GROUP,
    MESSAGE_WINDOW_SIZE,
    CHARACTER_TIMEOUT_SECONDS,
    TOTAL_GROUP_TIMEOUT_SECONDS,
    CONTINUE_ON_CHARACTER_FAILURE,
)

__all__ = [
    "CHAT_MODEL",
    "EMBEDDINGS_INDEXER_MODEL",
    "EMBEDDINGS_KB_MODEL",
    "HOST",
    "PORT",
    "OLLAMA_URL",
    "MAX_UPLOAD_SIZE",
    "ALLOWED_BOOK_EXTENSIONS",
    "ALLOWED_AVATAR_EXTENSIONS",
    "DATA_DIR",
    "CHARACTERS_DIR",
    "BOOKS_DIR",
    "AVATARS_DIR",
    "GROUPS_DIR",
    "CHROMA_DIR",
    "CHUNK_SIZE",
    "OVERLAP_PERCENTAGE",
    "OVERLAP_SIZE",
    "TTS_SERVICE_URL",
    "TTS_TIMEOUT",
    "TTS_OUTPUT_DIR",
    "TTS_MAX_TEXT_LENGTH",
    "STT_SERVICE_URL",
    "STT_TIMEOUT",
    "STT_MAX_FILE_SIZE",
    "STT_ALLOWED_FORMATS",
    "MAX_CHARACTERS_PER_GROUP",
    "MESSAGE_WINDOW_SIZE",
    "CHARACTER_TIMEOUT_SECONDS",
    "TOTAL_GROUP_TIMEOUT_SECONDS",
    "CONTINUE_ON_CHARACTER_FAILURE",
]
